#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

# Dump the configuration to stdout
# json.dump(config, fp=sys.stdout)
if os.path.exists("grist.env"): 
	data = agent.read_envfile("grist.env") 
	config["GRIST_SINGLE_ORG"] = data.get("GRIST_SINGLE_ORG", "grist") 
	config["GRIST_DEFAULT_EMAIL"] = data.get("GRIST_DEFAULT_EMAIL", "myemail") 
	config["APP_HOME_URL"] = data.get("APP_HOME_URL", "https://getgrist.local") 
else: 
	config["GRIST_SINGLE_ORG"] = "grist" 
	config["GRIST_DEFAULT_EMAIL"] = "myemail" 
	config["APP_HOME_URL"] = "https://getgrist.local" 
 
json.dump(config, fp=sys.stdout)
